name: java-locator CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Rust with Cargo
        run: cargo build --verbose
      - name: Test Rust with Cargo
        run: cargo test --verbose -- --nocapture

  # This is a good test for the locate-jdk-only feature, as the JRE is in a different path on JDK 8
  test-locate-jdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test Rust with Cargo
        run: JAVA_HOME="" cargo test --features=locate-jdk-only --verbose -- --nocapture
